def name_error():
    printx("the name error funciton")

name_error()

